# Generated by Django 3.1.7 on 2021-03-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_data_processing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
