# Generated by Django 3.1.7 on 2021-04-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('satellite_data_processing', '0002_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationAndIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('indicator', models.CharField(max_length=100)),
            ],
        ),
    ]
