# Generated by Django 3.1.7 on 2021-04-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_data_processing', '0004_auto_20210422_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='indicator',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
